name: Test
on: [push]
jobs:
  build:
    name: Build, lint, and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install deps
        run: yarn install

      - name: Check types
        run: yarn typecheck

      - name: Build
        run: yarn build

      - name: Jest run
        run: yarn test